var language_app; $(document).ready(function(){ language_app = {
    "profile": "Profile",
    "lb_company_logo": "Logo Perusahaan",
    "lb_company_name": "Nama Perusahaan",
    "lb_email": "Alamat Email",
    "lb_phone": "Nomor Telepon",
    "lb_password": "Kata Sandi",
    "lb_password_confirm": "Konfirmasi Kata Sandi",
    "lb_name": "Nama",
    "lb_first_name": "Nama Depan",
    "lb_last_name": "Nama Belakang",
    "lb_fullname": "Nama Lengkap",
    "lb_address": "Alamat",
    "lb_pos_code": "Kode Pos",
    "lb_city": "Kota",
    "lb_province": "Provinsi",
    "lb_state": "State",
    "lb_country": "Negara",
    "lb_action": "Tindakan",
    "lb_expire": "Kadaluarsa",
    "lb_device": "Perangkat",
    "lb_date": "Tanggal",
    "lb_startdate": "Tanggal Mulai",
    "lb_enddate": "Tanggal Akhir",
    "lb_transaction_no": "Nomor Transaksi",
    "lb_transaction_name": "Transaction Name",
    "lb_search": "Cari",
    "lb_search_data": "Cari Data",
    "lb_package": "Paket",
    "lb_status_remark": "Status & Catatan",
    "lb_voucher_package": "Paket Voucher",
    "lb_voucher_qty": "Jumlah Voucher",
    "lb_amount": "Total",
    "lb_qty": "Kuantitas",
    "lb_bank": "Bank",
    "lb_day": "Hari",
    "lb_week": "Minggu",
    "lb_month": "Bulan",
    "lb_year": "Tahun",
    "lb_yes": "Ya",
    "lb_no": "Tidak",
    "lb_voucher_code": "Kode Voucher",
    "lb_group_name": "Nama Grup",
    "lb_member_group": "Anggota Grup",
    "lb_headgroup": "Kepala Grup",
    "lb_remark": "Catatan",
    "lb_remark_employee": "Catatan Pegawai",
    "lb_location_remark": "Lokasi (Tandai lokasi mitra bisnis Anda pada peta di bawah)",
    "lb_t_status": "Status Transaksi",
    "lb_author": "Penulis",
    "lb_category": "Kategori",
    "lb_publish": "Menerbitkan",
    "lb_unpublish": "Batalkan Publikasi",
    "lb_meetwith": "Bertemu Dengan",
    "lb_group_report": "Laporan Grup",
    "lb_employee_name": "Nama Pegawai",
    "lb_use_date": "Tanggal Pakai",
    "lb_minute": "Menit",
    "lb_time": "Waktu",
    "lb_employee_history": "Riwayat Lokasi Karyawan",
    "lb_add_new_transaction": "Tambahkan Transaksi Baru",
    "lb_add_new_message": "Tambahkan Pesan Baru",
    "lb_add_new_employee": "Tambah Pegawai Baru",
    "lb_add_new_customer": "Tambah Customer Baru",
    "lb_add_new_group": "Tambah Grup Baru",
    "lb_add_new_content": "Tambah Konten Baru",
    "lb_subject": "Subjek",
    "lb_message": "Pesan",
    "lb_all": "Semua",
    "lb_login_account": "Masuk Akun",
    "lb_enter_verificationcode": "Masukan Kode Verifikasi",
    "lb_have_account": "Sudah punya akun ?",
    "lb_no_account": "Belum memiliki akun ?",
    "lb_register_now": "Daftar Sekarang",
    "lb_register_account": "Daftar Akun",
    "lb_forgot_password": "Lupa Kata Sandi ?",
    "lb_reset_password": "Setel Ulang Kata Sandi",
    "lb_send": "Kirim",
    "lb_verification_account": "Verifikasi Akun",
    "lb_resend_verification": "Kirim ulang kode verifikasi",
    "lb_user_another_account": "Pakai akun lain",
    "lb_customer_address": "Alamat Customer",
    "lb_customer_route": "Rute Customer",
    "lb_customer_segment": "Segmen pelanggan",
    "lb_apply": "Menerapkan",
    "lb_help_center": "Pusat Bantuan",
    "lb_total_employee_today": "Total Pegawai Hari Ini",
    "lb_total_troute_today": "Total Transaksi Rute Hari Ini",
    "lb_total_complete_route_today": "Total Rute Selesai Hari Ini",
    "lb_location_employee_today": "Lokasi Pegawai Hari Ini",
    "lb_status_employee": "Status Pegawai",
    "lb_finish": "Selesai",
    "lb_checkin": "Check In",
    "lb_checkout": "Check Out",
    "lb_language": "Bahasa",
    "lb_english": "inggris",
    "lb_indonesia": "Indonesia",
    "lb_check": "Cek",
    "lb_history": "Riwayat",
    "lb_employee_checkin": "Karyawan Check In",
    "lb_employee_checkout": "Karyawan Check Out",
    "lb_expire_date": "Tanggal Kadaluarsa",
    "lb_description": "Description",
    "lb_logout": "Keluar",
    "lb_user_account": "Akun Pengguna",
    "lb_manage": "Manajemen",
    "lb_company": "Perusahaan",
    "lb_t_voucher": "Transaksi Voucher",
    "lb_admin": "Administrasi",
    "lb_buy_voucher": "Pembelian Voucher",
    "lb_company_info": "Informasi Perusahaan",
    "lb_master": "Master",
    "lb_customer": "Customer",
    "lb_employee": "Pegawai",
    "lb_employee_group": "Grup Pegawai",
    "lb_transaction": "Transaksi",
    "lb_broadcast_msg": "Pesan Broadcast",
    "lb_t_route": "Transaksi Rute Pegawai",
    "lb_last_position": "Posisi Terakhir Pegawai",
    "lb_report": "Laporan",
    "lb_employee_route": "Rute Pegawai",
    "lb_route_employee": "Rute Kunjungan Pegawai",
    "lb_employee_visit_time": "Durasi Kunjungan  Pegawai",
    "lb_remark_note": "Keterangan dan Catatan",
    "lb_employee_visit": "Kunjungan Pegawai",
    "lb_content": "Konten",
    "lb_add_content": "Tambah Konten",
    "lb_blog": "Blog",
    "lb_faq": "FAQ",
    "lb_setting": "Pengaturan",
    "lb_op_save_customer": "Opsi Simpan Customer",
    "lb_detail_info": "Detail Info",
    "lb_total_distance": "Total Jarak",
    "lb_duration": "Durasi",
    "lb_customer_place": "Tempat Customer",
    "lb_customer_location": "Lokasi Customer",
    "lb_customer_radius": "Radius Customer",
    "lb_total_visit": "Total Kunjungan",
    "lb_total_route": "Total Rute",
    "lb_total_plan_route": "Total Rute Direncanakan",
    "lb_total_miss_route": "Total Rute Tidak Selesai",
    "lb_total_unplan_route": "Total Rute Tidak Direncanakan",
    "lb_checkin_address": "Alamat Check In",
    "lb_checkout_address": "Alamat Check Out",
    "lb_checkin_time": "Waktu Check In",
    "lb_checkout_time": "Waktu Check Out",
    "btn_save_change": "Simpan Perubahan",
    "btn_save_user_account": "Simpan Akun Pengguna",
    "btn_save_company": "Simpan Informasi Perusahaan",
    "btn_save": "Simpan",
    "btn_close": "Tutup",
    "btn_cancel": "Batal",
    "btn_view": "Lihat",
    "btn_view_voucher": "Lihat Voucher",
    "btn_undelete": "Batal Hapus",
    "btn_delete": "Hapus",
    "btn_edit": "Ubah",
    "btn_add_customer": "Tambah Customer Baru",
    "btn_buy_voucher": "Beli Voucher",
    "btn_skip": "Lewati",
    "btn_confirmation": "Konfirmasi",
    "btn_unlink": "Batalkan tautan",
    "btn_generate_token": "Buat token",
    "btn_set_superadmin": "Jadikan super admin",
    "btn_save_ascustomer": "Simpan sebagai customer",
    "btn_delete_privilege": "Hapus Privilege",
    "btn_detail": "Detail",
    "btn_view_serial": "View Serial",
    "btn_customer_price": "Customer Price",
    "btn_active": "Active",
    "btn_nonactive": "Nonactive",
    "btn_back": "Back",
    "btn_action": "Action",
    "lb_choose_voucher_package": "Pilih Paket Voucher",
    "lb_choose_voucher_qty": "Pilih Jumlah Voucher",
    "lb_choose_headgroup": "Pilih Kelapa Grup",
    "lb_choose_t_status": "Pilih Status Transaksi",
    "lb_choose_report": "Pilih Laporan",
    "lb_chosse_employee_name": "Pilih Nama Pegawai",
    "lb_choose_company_name": "Pilih Nama Perusahaan",
    "lb_choose_minute": "Pilih Menit",
    "lb_choose_customer": "Pilih Nama Customer",
    "lb_note": "Catatan",
    "note_voucher": "Nomor Akun dan Jumlah Transfer akan dikirim melalui Email Untuk memudahkan memeriksa jumlah transfer akan ditambahkan nomor unik. Contoh IDR. 49,123.00",
    "note_voucher2": "Pembelian voucher di atas 17:00 WIB, akan diproses pada hari berikutnya.",
    "note_employee": "Master Pegawai digunakan untuk mengelola Penjualan, Teknisi, Kurir, Pengemudi, dll.",
    "note_img": "Ukuran file maks. 2mb, format (PNG, JPG, JPEG)",
    "note_forgot_password": "Petunjuk telah dikirim, Silakan periksa email anda",
    "note_register": "Daftar akun baru berhasil, silakan periksa email atau no handphone Anda untuk melakukan verifikasi akun anda",
    "v_email_empty": "Alamat email tidak boleh kosong",
    "v_email_not_registered": "Maaf alamat email anda tidak terdaftar",
    "v_password_empty": "Kata sandi tidak boleh kosong",
    "v_password_wrong": "Kata sandi salah",
    "v_account_deadactive": "Maaf akun anda tidak aktif",
    "v_account_not_headgroup": "Maaf akun anda bukan kepala grup",
    "v_email_already": "Akun dengan alamat email ini sudah ada",
    "v_phone_already": "Akun dengan nomor telepon ini sudah ada",
    "v_email_format": "Format alamat email salah",
    "v_name_empty": "Silakan isi nama",
    "v_phone_empty": "Silakan isi nomor telepon",
    "v_company_name_empty": "Silakan ini nama perusahaan",
    "v_company_not_registered": "Perusahaan tidak terdaftar",
    "v_employee_404": "Akun pegawai tidak ditemukan",
    "v_company_deadactive": "Akun perusahaan belum aktif",
    "v_account_deadactive_cek": "Akun anda belum aktif. Silakan cek email atau nomor telepon untuk verifikasi akun perusahaan ",
    "v_date_empty": "Silkan isi tanggal",
    "v_subject_empty": "Silakan isi subjek",
    "v_message_empty": "Silakan isi pesan",
    "v_select_voucher_package": "Silakan pilih paket voucher",
    "v_select_bank": "Silakan pilih bank",
    "v_select_qty": "Silakan pilih jumlah voucher",
    "v_transfer_date_empty": "Silakan isi tanggal transfer",
    "v_account_bank_empty": "Silakan isi nama akun bank",
    "v_account_number_empty": "Silakan isi nama nomor rekening",
    "v_transfer_amount": "Silakan isi jumlah transfer",
    "v_group_name": "Silakan isi nama grup",
    "v_headgroup": "Silakan isi kepala grup",
    "v_membergroup": "Silakan isi anggota grup",
    "v_fullname": "Silakan isi nama lengkap",
    "v_customer_name": "Silakan isi nama customer",
    "v_login_fail": "Gagal Masuk",
    "v_password_reset": "Password anda telah disetel ulang silakan coba untuk login",
    "v_verificationcode_empty": "Verifikasi kode tidak boleh kosong",
    "v_verificationcode_wrong": "Kode verifikasi anda salah",
    "v_verificationcode_expire": "nomor verifikasi Anda sudah kadaluarsa, harap kirim ulang nomor verifikasi baru",
    "v_verificationcode_success": "Verifikasi akun anda berhasil",
    "v_sendnew_verificationcode": "Kode verifikasi kode baru telah dikirim ke alamat email",
    "v_sendnew_verificationcode_fail": "Gagal mengirim verifikasi kode baru ke alamat email",
    "v_sendnew_verificationcode2": "Kode verifikasi kode baru telah dikirim ke nomor telepon",
    "v_sendnew_verificationcode_fail2": "Gagal mengirim verifikasi kode baru ke nomor telepon",
    "v_xchange_resend_vercode1": "Ubah alamat email dan kirim kode verifikasi baru gagal",
    "v_xchange_resend_vercode2": "Ubah nomor telepon dan kirim kode verifikasi gagal",
    "v_achange_resend_vercode1": "Ubah alamat email berhasil dan",
    "v_achange_resend_vercode2": "Ubah nomor handphone berhasil dan",
    "v_password1": "kata sandi Anda harus mengandung setidaknya 8 karakter",
    "v_password2": "Kata Sandi Anda Harus Berisi Sedikitnya 1 Angka",
    "v_password3": "Kata Sandi Anda Harus Mengandung Sedikitnya 1 Huruf Kapital",
    "v_password4": "Kata Sandi Anda Harus Berisi Sedikitnya 1 Huruf Kecil",
    "v_address_empty": "Silakan isi alamat",
    "lb_selling": "Sales Order",
    "lb_sellingno": "Sales Order No",
    "lb_selling_date": "Sales Order Date",
    "lb_deliveryno": "Delivery No",
    "lb_deliveryqty": "Qty Delivery",
    "lb_purchase": "Purchase Order",
    "lb_purchase2": "Purchase",
    "lb_purchaseno": "Purchase No",
    "lb_goodrc": "Good Receipt",
    "lb_goodrcno": "Receive No",
    "lb_goodrc_date": "Receive Date",
    "lb_invoicear": "Receivables Invoice",
    "lb_invoiceap": "Payable Invoice",
    "lb_delivery": "Item Delivery",
    "lb_delivery_total": "Total Item Delivery",
    "lb_delivery1": "Delivery",
    "lb_paymentar": "Receivables Payment",
    "lb_paymentap": "Payable Payment",
    "lb_returnar": "Sales Return",
    "lb_returnar_total": "Total Sales Return",
    "lb_returnap": "Purchase Return",
    "lb_correctionar": "Receivables Correction",
    "lb_correctionap": "Payable Correction",
    "lb_correctionstore": "Store Correction",
    "lb_paymentstore": "Sales Payment",
    "lb_return_receipt": "Return Receipt",
    "lb_journal": "Journal",
    "lb_sales_retail": "Sales Retail",
    "lb_cost_sold": "Cost Of Goods Sold",
    "lb_stock_opname": "Stock Opname",
    "lb_stock_correction": "Stock Correction",
    "lb_stock_mutation": "Stock Mutation",
    "lb_cash": "Cash",
    "lb_giro": "Giro",
    "lb_girono": "Giro No",
    "lb_bank_name": "Bank Name",
    "lb_bank_acount": "Account Name",
    "lb_bank_acountno": "Account No",
    "lb_transfer": "Transfer",
    "featuresx": "Fitur Pipesys",
    "features": "Fitur",
    "price": "Harga",
    "user": "Pengguna",
    "month": "Bulan",
    "year": "Tahun",
    "module": "Modul",
    "person": "Orang",
    "max": "Maks",
    "login": "Masuk",
    "try_free": "Coba Gratis",
    "try_free_now": "Coba gratis sekarang juga",
    "free_trial": "Gratis percobaan selama 30 hari",
    "help_center": "Pusat Bantuan",
    "another_product": "Produk Lain",
    "contact": "Kontak",
    "module_detail": "Detail Modul",
    "additional": "Tambah Pengguna",
    "buy_voucher": "Beli Voucher",
    "fitur_dashboard": "Dashboard",
    "fitur_purchase": "Modul Pembelian",
    "fitur_sales": "Modul Penjualan",
    "fitur_stock": "Stok Barang",
    "fitur_accounting": "Akunting",
    "lb_try_it_now": "Try It Now",
    "fitur_dashboard_txt": "Tampilan dashboard yang menarik dan informatif dengan menyajikan data pembelian, penjualan dan inventory",
    "fitur_purchase_txt": "Membantu proses pembelian mulai dari purchase order, good receipt, return purchase sampai payment payable",
    "fitur_sales_txt": "Membantu proses penjualan mulai dari Sales order, delivery, return sales sampai payment receivable",
    "fitur_stock_txt": "Membantu monitoring stok keluar dan masuk seperti transaksi correction stock, stock opname, mutation stock",
    "fitur_accounting_txt": "Membantu untuk mempersiapkan laporan keuangan mulai dari jurnal otomatis pada setiap transaksi serta pencatatan masuk & keluar arus kas dan bank",
    "slogan": "Membantu proses bisnis dalam transaksi pembelian, penjualan, stock inventaris dan akunting",
    "slide_1": "Atur proses bisnis menjadi lebih mudah dengan Pipesys (POS)",
    "lb_choose_qty": "Please choose Qty",
    "lb_email_format": "Invalid Email format",
    "lb_email_empty": "Email can't be null",
    "lb_name_empty": "Name can't be null",
    "lb_store_name_empty": "Store name can't be null",
    "lb_information": "Information",
    "lb_incomplete_form": "Incomplete form",
    "lb_alert_order": "Are you sure want to order?",
    "lb_order": "Order",
    "lb_canceled": "Canceled",
    "lb_name_validate": "Only letters and space allowed",
    "lb_type_empty": "Type can't be null",
    "lb_first_name_empty": "First name can't be null",
    "lb_lasr_name_empty": "Last name can't be null",
    "lb_instruction": "Instructions sent, Please check your e-mail",
    "lb_reset": "Reset",
    "lb_send_to_email": "Send to Email",
    "lb_send_to_phone": "Send to Phone Number",
    "lb_user_info": "User Information",
    "lb_agree_terms": "I agree with terms and policy",
    "lb_noted": "Noted",
    "lb_email_provide": "Please provide a valid email address, payment instruction and voucher code will be sent to the email address provided here after completeting the order.",
    "lb_account_ex": "Account Number and Transfer Amount will be sent by Email To facilitate checking the number of transfers will be added a unique number. Example IDR. 49,123.00",
    "lb_voucer_continue": "Continue Buy Voucher",
    "lb_voucher_module": "Module \/ Device Voucher Qty",
    "lb_voucher_module_choose": "Choose Voucher Module \/ Devices Quantity",
    "lb_voucher_module_amount": "Total Price : Module \/ Device Voucher",
    "lb_voucher_user": "Additional User Voucher Qty",
    "lb_voucher_user_choose": "Choose Voucher Additional User Quantity",
    "lb_voucher_user_amount": "Total Price : Additional User Voucher",
    "lb_voucher_additional": "Voucher Additional User",
    "lb_voucher_notif": "Thank you for purchasing voucher from us",
    "lb_voucher_code1": "Your order code is ",
    "lb_voucher_confirm": "You will receive a confirmation email with your order details",
    "lb_voucher_detail": "Detail Order",
    "lb_voucher_type": "Voucher Type",
    "lb_voucher_type_choose": "Please choose voucher type",
    "lb_voucher_use": "Use Voucher",
    "lb_voucher_empty": "Voucer Code can't be null",
    "lb_voucher_not_found": "Voucher Code not found",
    "lb_user_expired": "Expired User",
    "lb_user_expired_validate": "Your Account has expired",
    "lb_store": "Store",
    "lb_for_additional": "for additional user",
    "lb_additional_qty": "Additional Quantity",
    "lb_module_qty": "Module \/ Devices Quantity",
    "lb_module_device": "Module \/ Devices",
    "lb_use_voucher": "Voucher Use",
    "lb_voucher_enter": "Enter Voucher Code",
    "lb_voucher_enter_validate": "Please enter voucher code",
    "lb_module_validate": "Please select module",
    "lb_total_amount": "Grand Total",
    "lb_check_out": "Checkout",
    "lb_loading": "Loading",
    "lb_reload": "Reload",
    "lb_close": "Close",
    "lb_add_new": "Add New",
    "lb_error_data": "Error data, please try again",
    "lb_error_data1": "Error deleting data",
    "lb_user_not_found": "Account user not found",
    "lb_success": "Success",
    "lb_days": "Days",
    "lb_hours": "Hours",
    "lb_minutes": "Minutes",
    "lb_seconds": "Seconds",
    "lb_startdate_select": "Select Start Date",
    "lb_enddate_select": "Select End Date",
    "lb_total_sales_amount": "Total Sales Amount",
    "lb_total_gross_margin": "Total Gross Margin",
    "lb_total_purchase_amount": "Total Purchase Amount",
    "lb_module_device_expire": "Module\/Devices & Additional User Expires",
    "lb_module_expire": "Module Expire",
    "lb_day_left": "Day Left",
    "lb_device_expire": "Device Expire",
    "lb_sales": "Sales",
    "lb_total_by_category": "Total Sales By Category",
    "lb_top_by_category": "Top 5 Sales by Category",
    "lb_top_by_customer": "Top 10 Sales by Customer",
    "lb_top_by_city": "Top 10 Sales by City",
    "lb_total_sales_transaction": "Total Sales Transaction",
    "lb_outstanding_sales": "Outstanding Sales",
    "lb_total_store_sales": "Total Store Sales",
    "lb_total_store": "Total Store",
    "lb_total_customer": "Total Customer",
    "lb_open_selling": "Open Selling",
    "lb_total_open_selling": "Total Open Selling",
    "lb_overdude_selling": "Overdue Selling",
    "lb_total_overdude_selling": "Total Overdue Selling",
    "lb_payment_receivable": "Payment Receivable",
    "lb_total_payment": "Total Payment",
    "lb_purchase1": "Purchase",
    "lb_total_purchse_qty": "Total Purchase Quantity",
    "lb_total_receipt_qty": "Total Good Receipt Quantity",
    "lb_total_purchse_trans": "Total Purchase Transaction",
    "lb_total_penerimaan_trans": "Total Good Receipt Transaction",
    "lb_total_product_return": "Total Product Return",
    "lb_open_purchase": "Open Purchases",
    "lb_open_purchase_total": "Total Open Purchases",
    "lb_overdude_purchase": "Overdue Purchases",
    "lb_overdude_purchase_total": "Total Overdue Purchases",
    "lb_payment_purchase": "Payment Purchases",
    "lb_payment_purchase_total": "Total Payment Purchases",
    "lb_inventory": "Inventory",
    "lb_inventory_select": "Select Inventory",
    "lb_total_stock": "Total Stock",
    "lb_stock_minimal": "Stock Product Minimal",
    "lb_total_product": "Total Product",
    "lb_total_omset": "Total Omset",
    "lb_omset": "Omset",
    "lb_total_sales_store_ar": "Total Sales Store Receivable",
    "lb_total_net_profit": "Total Net Profit",
    "lb_total_net_balance": "Total Net Balance Sheet",
    "lb_ac_watchlist": "Account Watchlist",
    "lb_total": "Total",
    "lb_sales_by_hour": "Sales by Hour",
    "lb_store_location": "Store Location",
    "lb_additional_expire": "Additional User Expire",
    "lb_product_code": "Product Code",
    "lb_product_name": "Product Name",
    "lb_minimal_stock": "Minimal Stock",
    "lb_residu": "Residu Stock",
    "lb_select_file": "Please Select File",
    "lb_select_type": "Select Type",
    "lb_deleted": "Yes, delete it!",
    "lb_deleted1": "Deleted",
    "lb_ask": "Are you sure?",
    "lb_undeleted": "Yes, undelete it!",
    "lb_canceled1": "No, cancel it!",
    "lb_transaction_status": "Status Transaction",
    "lb_account_no": "Account Number",
    "lb_transfer_amount": "Transfer Amount",
    "lb_voucher_confirm1": "Voucher Confirmation",
    "lb_add_form_voucher": "Add Form Voucher",
    "lb_delete_form_voucher": "Delete Form Voucher",
    "lb_trans_process": "Transaction Process",
    "lb_trans_success": "Transaction Success",
    "lb_trans_cancel": "Transaction Cancel",
    "lb_add_bank": "Add Bank",
    "lb_branch_name": "Branch Name (Bank)",
    "lb_remove_bank": "Remove Bank",
    "lb_remove_module": "Remove Module",
    "lb_bank_min_1": "Sorry, Bank Minimum 1",
    "lb_bank_max": "Sorry, Bank Maximum Added",
    "lb_save_setting": "Save Setting",
    "lb_ac": "Accounting",
    "lb_type": "Type",
    "lb_image": "Image",
    "lb_selling1": "Selling",
    "lb_fax": "Fax",
    "lb_remove": "Remove",
    "lb_process": "Process",
    "lb_used_by_name": "Used By (Name)",
    "lb_used_by_com": "Used By (Company Name)",
    "lb_currency": "Currency",
    "lb_select_module": "Select Module",
    "lb_module_purchase": "Module Purchase",
    "lb_module_selling": "Module Selling",
    "lb_module_inventory": "Module Inventory",
    "lb_module_ac": "Module Accounting",
    "lb_devices": "Devices",
    "lb_stock": "Stock",
    "lb_mutation": "Mutation",
    "lb_cash_bank": "Cash \/ Bank",
    "lb_payment": "Payment",
    "lb_correction": "Correction",
    "lb_invoice": "Invoice",
    "lb_return": "Return",
    "lb_recipt": "Receipt",
    "lb_npwp": "NPWP",
    "lb_ok": "OK",
    "lb_amount_digint": "Amount \/ Price Decimal Digit",
    "lb_decimal_digit": "Quantity Decimal Digit",
    "lb_cost_method": "Costing Method",
    "lb_average": "Average",
    "lb_negative": "Negative Stock",
    "lb_allow": "Allow",
    "lb_warning": "Warning",
    "lb_block": "Block",
    "lb_send_debt": "Send Report Debt & Receivable Every",
    "lb_monday": "Monday",
    "lb_tuesday": "Tuesday",
    "lb_wednesday": "Wednesday",
    "lb_thursday": "Thursday",
    "lb_friday": "Friday",
    "lb_saturday": "Saturday",
    "lb_sunday": "Sunday",
    "lb_module_setting": "Module Setting",
    "lb_journal_manual": "Journal Manual",
    "lb_data_setting": "Data Setting",
    "lb_template_default": "Default Template Setting",
    "lb_data_default": "Default Data Setting",
    "lb_view_image": "View Image",
    "lb_manage_store": "Store & Device Management",
    "lb_store_name": "Store Name",
    "lb_store_not_found": "Store not found, Please check store again",
    "lb_location_marker": "Location (Mark your store location on the map below)",
    "lb_locked": "Locked",
    "lb_unlocked": "Unlocked",
    "lb_coa_setting": "COA Setting",
    "lb_coa_ap": "COA Payable",
    "lb_ap": "Account Payable",
    "lb_ap_temp": "Account Payable Temporary",
    "lb_tax_in": "Tax In",
    "lb_tax_out": "Tax Out",
    "lb_tax_in_temp": "Tax In Temporary",
    "lb_tax_out_temp": "Tax Out Temporary",
    "lb_discount": "Discount",
    "lb_discount_value": "Discount Value",
    "lb_coa_ar": "COA Receivable",
    "lb_ar": "Account Receivable",
    "lb_ar_temp": "Account Receivable Temporary",
    "lb_sales_temp": "Sales Temporary",
    "lb_income": "Income",
    "lb_expense": "Expense",
    "lb_delivery_cost": "Delivery Cost",
    "lb_gains_stock": "Gains Stock",
    "lb_loss_stock": "Loss Stock",
    "lb_transfer_credit": "Transfer\/Credit",
    "lb_profit_year": "Profit And Loss Current Year",
    "lb_select_data": "select data",
    "lb_code": "Code",
    "lb_level": "Level",
    "lb_coa_parent": "Parent COA",
    "lb_coa_without": "Without COA",
    "lb_product_item": "Item Product",
    "lb_product_service": "Service",
    "lb_delete": "Delete",
    "lb_selling_select": "Select Selling",
    "lb_min_qty": "Min Quantity",
    "lb_unit": "Unit",
    "lb_purchase_price": "Purchase Price",
    "lb_selling_price": "Selling Price",
    "lb_average_price": "Average Price",
    "lb_product_code_note": "Left blank, Product code will be generate automatically by system",
    "lb_product_type": "Product Type",
    "lb_product_type_select": "Select Product Type",
    "lb_serial": "Serial",
    "lb_sn_format": "Serial Number Format",
    "lb_sn_format_note": "The Serial Number will be created automatically by the system. Click here to set the serial number format",
    "lb_auto": "AUTOMATIC",
    "lb_before_tax": "Price before tax",
    "lb_product_inventory_note": "The stock will be recorded and monitored by system.",
    "lb_product_selling_note": "This item can be sell.",
    "lb_product_serial_note": "This item have serial number.",
    "lb_product_qty_note": "Min Qty used for minimal stock product information.",
    "lb_product_code_exist": "Sorry this product code has been already exist",
    "lb_product_name_empty": "Product name can't be null",
    "lb_category_empty": "Category can't be null",
    "lb_unit_empty": "Unit can't be null",
    "lb_product_serial": "Prduct Serial Number",
    "lb_import_detail": "Import Data Detail",
    "lb_failed": "Failed",
    "lb_product_insert": "Insert Master Product",
    "lb_product_update": "Update Master Product",
    "lb_category_insert": "Insert Master Category",
    "lb_category_update": "Update Master Category",
    "lb_data_not_found": "Data Not Found",
    "lb_total_data": "Total Data",
    "lb_fail": "Fail",
    "lb_file_not_found": "File not found, please reupload import file",
    "lb_next": "Next",
    "lb_saving": "Saving",
    "lb_remarks": "Remarks",
    "lb_remark_input": "Input Remark",
    "lb_qty_input": "Input Qty",
    "lb_price_input": "Input Price",
    "lb_discount_input": "Input Discount",
    "lb_average_input": "Input Average",
    "lb_attachment": "Attachment",
    "lb_file_upload": "File Upload",
    "lb_file_choose": "Choose file in brwoser",
    "lb_code_required": "Code is required and not duplicate.",
    "lb_name_not_change": "Name is required and can't change.",
    "lb_average_required": "Average Price is required.",
    "lb_price_required": "Price is required.",
    "lb_stock_op_required": "Stock Opname Qty is required.",
    "lb_stock_qty_not_change": "Stock Qty is required and can't change.",
    "lb_unit_not_change": "Unit is required and can't change.",
    "lb_remark_opsional": "Remark is opsional filed.",
    "lb_sn_reqired": "products with serial numbers must be 1 quantity and is required. and not duplicate",
    "lb_average_price_program": "Average price program and Average price input is not balance",
    "lb_product_not_found": "Product not found, Please check your data",
    "lb_product_name_not_change": "Can't change Product Name",
    "lb_unit_not_change1": "Can't change Product Unit",
    "lb_stock_qty_not_change1": "Can't change Stock Qty",
    "lb_product_code_not_found": "Product Code not found",
    "lb_product_code_or_branch_not_fount": "Product Code or Store not found",
    "lb_average_number": "Input Average Price With Number Format",
    "lb_stock_opname_qty_num": "Input Stock Opname Qty With Number Format",
    "lb_stock_qty_num": "Input Stock Qty With Number Format",
    "lb_uom": "Unit of Measurement",
    "lb_category_not_data": "Item Category is empty.",
    "lb_category_add": "Please add new Category first",
    "lb_store_required": "Store is required.",
    "lb_average_view": "View Average",
    "lb_product_store": "Product Store",
    "lb_category_code": "Category Code",
    "lb_category_name": "Category Name",
    "lb_product_download": "Download sample template Product excel file from",
    "lb_here": "here",
    "lb_file_note": "This file has preset column header required by PipeSys to import your data correctly.",
    "lb_file_entry": "Entry Data To File Template.",
    "lb_use_excell": "Use Microsoft Excel application to copy and paste your data into Pipesys import template that you just downloaded. Make sure the data you that you input corresponds to each column header provided on the import template and note below.",
    "lb_product_code_note1": "If Product Code is empty then system will auto generate product code.",
    "lb_category_code_note": "Category Code is required and can see in Master Category.",
    "lb_category_name_note": "Category Name is required and can see in Master Category.",
    "lb_product_name_requi": "Product Name is required.",
    "lb_min_qty_note": "Mininum quantity of product.",
    "lb_unit_note": "Unit is required and can se in Master Unit.",
    "lb_selling_price_requi": "Selling Price is required.",
    "lb_product_type_requi": "Pruduct Type is required, Ex: Yes, No.",
    "lb_selling_type_requi": "Selling Type is required, Ex: Yes, No.",
    "lb_serial_type_requi": "Serial Type is required, Ex: Yes, No.",
    "lb_upload_file": "Upload File",
    "lb_file_type": "After your finished with step 2, please upload the file. File needs to be in CSV (Comma Separated Values) format and ended with extension .xls",
    "lb_excell_note": "New excel format applied, if you already have one please update your excel to the latest format before uploading!",
    "lb_excell_empty": "Please Upload Excel File",
    "lb_category_inactive": "Category Code has been inactive",
    "lb_inventory_not_change": "Update can't change Inventory type",
    "lb_selling_not_change": "Update can't change Selling type",
    "lb_serial_not_change": "Update can't change Serial type",
    "lb_product_inactive": "Product Code has been inactive",
    "lb_inventory_type_empty": "If inventory type yes unit can't be null",
    "lb_price_input_format": "Input Price With Number Format",
    "lb_inventory_only_use": "Inventory Type only use Yes or No",
    "lb_selling_only_use": "Selling Type only use Yes or No",
    "lb_serial_only_use": "Serial Type only use Yes or No",
    "lb_selling_zero": "Should field Selling Price is Zero, because Selling Type is No",
    "lb_category_code_empty": "Category Code can't be null",
    "lb_category_name_empty": "Category Name can't be null",
    "lb_column_not_match": "Column not match",
    "lb_success_import": "Success import data",
    "lb_file_not_found1": "File not found, please reupload import file",
    "lb_import_alert": "NOTE: New excel format applied, if you already have one please update your excel to the latest format before uploading!",
    "lb_sales_import1": "1. Download sample template Sales excel file from",
    "lb_sales_import2": "2. Entry Data To File Template",
    "lb_sales_import3": "3. Upload File",
    "lb_sales_import1_note1": "This file has preset column header required by PipeSys to import your data correctly",
    "lb_sales_import2_note1": "Use Microsoft Excel application to copy and paste your data into Pipesys import template that you just downloaded. Make sure the data you that you input corresponds to each column header provided on the import template and note below.",
    "lb_sales_import2_note2": "Sales Code: Sales Code is required and no duplicate",
    "lb_sales_import2_note3": "Name: fill in the name of sales",
    "lb_sales_import2_note4": "Phone: fill in the Phone of sales",
    "lb_sales_import2_note5": "City: fill in the City of sales",
    "lb_sales_import2_note6": "Address: fill in the Address of sales",
    "lb_sales_import2_note7": "Remark: fill in the Remark of sales",
    "lb_sales_import3_note3": "After your finished with step 2, please upload the file. File needs to be in CSV (Comma Separated Values) format and ended with extension .xls",
    "lb_reset_data": "Reset Data",
    "lb_reset_type": "Type Reset",
    "lb_reset_only_trans": "Only Transaction",
    "lb_reset_only_trans1": "Only Transaction Data",
    "lb_reset_all": "All (Master & Transaction)",
    "lb_username": "User Name",
    "lb_reset_alert": "Are you sure want to reset data?",
    "lb_reset_note": "\"Reset Data\" will delete all master data and transaction data, All information devices in the company will be deleted, and all branches or stores will unlink the device. Please understand before using this function.",
    "lb_reset_success": "Reset Data Success",
    "lb_status_select": "Select Status",
    "lb_vendor": "Vendor",
    "lb_vendor_select": "Select Vendor",
    "lb_qty_total": "Total Quantity",
    "lb_qty_total_real": "Total Real Quantity",
    "lb_sales_select": "Select Sales",
    "lb_term": "Term",
    "lb_due_date": "Due Date",
    "lb_tax": "Tax",
    "lb_qty_stock": "Qty Stock",
    "lb_qty2": "Qty",
    "lb_qty_warehouse": "Warehouse Qty",
    "lb_qty_real": "Real Qty",
    "lb_qty_real1": "Real Quantity",
    "lb_qty_hand": "Qty in Hand",
    "lb_qty_order": "Qty Order",
    "lb_conversion": "Conversion",
    "lb_sub_total": "Sub Total",
    "lb_delivery_date": "Delivery Date",
    "lb_add_column": "Add Column",
    "lb_discount_total": "Total Discount",
    "lb_select_product_empty": "Please select product",
    "lb_product_qty_empty": "Qty product can't be null",
    "lb_sales_empty": "Sales can't be null",
    "lb_vendor_empty": "Vendor can't be null",
    "lb_address_empty": "Address can't be null",
    "lb_city_empty": "City can't be null",
    "lb_province_empty": "Province can't be null",
    "lb_billing_empty": "BillingTo can't be null",
    "lb_max_item": "Item data max",
    "lb_print": "Print",
    "lb_sales_employee": "Sales & Employee",
    "lb_code_exist": "Code has been already exist",
    "lb_sales_name": "Sales Name",
    "lb_sales_without": "Without Sales",
    "lb_sales_code": "Sales Code",
    "lb_sales_note": "Left blank, Sales Code will be generate automatically by system",
    "lb_sales_inactive": "Sales Code has been inactive",
    "lb_product_duplicate": "Product can't duplicate",
    "lb_serial_empty": "Serial number can't be null",
    "lb_serial_not_found": "Serial not found",
    "lb_product_qty_stock": "Qty product is not available",
    "lb_service_not_serial": "Product Service can't input serial number",
    "lb_serial_not_active": "Product Serial not active, can't input serial number",
    "lb_serial_qty": "Product Serial must be 1 quantity",
    "lb_serial_duplicate": "Serial Number is duplicate",
    "lb_general": "General",
    "lb_site_profile": "Site Profile",
    "lb_site_title": "Site Title",
    "lb_site_tagline": "Site Tagline",
    "lb_generate_file": "Generate File",
    "lb_generate_language": "Generate Language JS",
    "lb_logo": "Logo",
    "lb_logo_small": "Small Logo",
    "lb_telephone": "Telephone",
    "lb_whatsapp": "Whatsapp",
    "lb_address_link": "Link Address to Maps",
    "lb_technical": "Technical",
    "lb_vendor_without": "Without Customers",
    "lb_vendor_name": "Vendor Name",
    "lb_partner_code": "Partner Code",
    "lb_delivery_address": "Delivery Address",
    "lb_delivery_city": "Delivery City",
    "lb_delivery_province": "Delivery Province",
    "lb_payment_to": "Payment To",
    "lb_payment_address": "Payment Address",
    "lb_payment_city": "Payment City",
    "lb_payment_province": "Payment Province",
    "lb_total_paid": "Total Paid",
    "lb_pay_cash": "Pay Cash",
    "lb_pay_transfer": "Pay Transfer",
    "lb_pay_giro": "Pay Giro",
    "lb_transaction_type": "Transaction Type",
    "lb_balance_type": "Balance Type",
    "lb_pay_total": "Total Pay",
    "lb_total_unpaid": "Total Unpaid",
    "lb_payment_date": "Payment Date",
    "lb_payment_type": "Payment Type",
    "lb_payment_method": "Payment Method",
    "lb_transaction_date": "Transaction Date",
    "lb_select_item": "Please select item",
    "lb_payment_method_empty": "Payment Method can't be null",
    "lb_paid_incorect": "Total Payment and Total Paid is incorrect",
    "lb_coa_select": "Select COA",
    "lb_paymentno": "Payment No",
    "lb_pay_credit_debit": "Pay Debit \/ Credit",
    "lb_pay_additional": "Additional Cost",
    "lb_grand_total_sales": "Grand Total Sales",
    "lb_total_sales": "Total Sales",
    "lb_order_type": "Type Order",
    "lb_purchase_non": "Non Purchase Order",
    "lb_delivery_order": "Delivery Order No",
    "lb_receipt_qty": "Qty Receive",
    "lb_purchase_date": "Purchase Date",
    "lb_vendor_select2": "Please select vendor",
    "lb_edit": "Edit",
    "lb_cancel_alert": "Are you sure want to cancel?",
    "lb_delete_alert": "Are you sure want to delete?",
    "lb_delivery_empty": "Delivery Order Code can't be null",
    "lb_paid_exceeding": "Total Paid exceeding Total Unpaid",
    "lb_paid_empty": "Total Paid can't be null",
    "lb_receipt_name": "Receipt Name",
    "lb_purchase_qty": "Purchase Qty",
    "lb_return_qty": "Return Qty",
    "lb_receipt_qty_empty": "Qty Receive is not available",
    "lb_customer_empty": "Customer can't be null",
    "lb_remark_empty": "Remark can't be null",
    "lb_receipt_no_empty": "Receive No can't be null",
    "lb_return_date": "Return Date",
    "lb_transaction_qty": "Transaction Qty",
    "lb_sales_qty_empty": "Qty Sell is not available",
    "lb_delivery_qty_empty": "Qty delivery is not available",
    "lb_grand_total": "Grand Total",
    "lb_invoice_date": "Invoice Date",
    "lb_invoiceno": "Invoice No",
    "lb_customer_select": "Please select customer",
    "lb_customer_select1": "Select customer",
    "lb_data_exists": "Data already exists",
    "lb_total_ar_invoice": "Total AR Invoice",
    "lb_correction_type": "Correction Type",
    "lb_correction_total": "Total Correction",
    "lb_debit": "Debit",
    "lb_credit": "Credit",
    "lb_correction_total_ap": "Total Correction AP",
    "lb_correction_total_ar": "Total Correction AR",
    "lb_store_select": "Select Store",
    "lb_input_nominal": "Input Nominal",
    "lb_correction_total_empty": "Total Correction can't null",
    "lb_store_select1": "Please select store",
    "lb_product_inventory_active": "Product Inventory must be active",
    "lb_product_duplicate2": "Product Code is duplicate",
    "lb_open": "Open",
    "lb_unpaid": "Unpaid",
    "lb_paid": "Paid",
    "lb_customer_name": "Customer Name",
    "lb_delivery_to": "Delivery To",
    "lb_billing_to": "Billing To",
    "lb_product_preorder": "Product is pre order",
    "lb_delivery_to_empty": "DeliveryTo can't be null",
    "lb_sales_order_non": "Non Sales Order",
    "lb_sales_qty": "Qty Sales",
    "lb_sales_all": "All Sales Order No",
    "lb_select": "Select",
    "lb_date_empty": "Date can't be null",
    "lb_total_ar_empty": "Total ar invoice can't be null",
    "lb_grand_total_empty": "Grand total can't be null",
    "lb_total_not_same": "Total Payment and Total AR Invoice must be same",
    "lb_sales_no_select": "Please Select Sales No",
    "lb_sale": "Sale",
    "lb_total_debit": "Total Debit",
    "lb_total_credit": "Total Credit",
    "lb_coa_code": "Coa Code",
    "lb_coa_name": "Coa Name",
    "lb_debit_or_credit_empty": "Debit or credit can't be null",
    "lb_coa_select1": "Please select COA",
    "lb_debit_credit_not_same": "Total debit and credit not balance",
    "lb_average_program": "Average Price Program",
    "lb_stock_opname_qty": "Stock Opname Qty",
    "lb_stock_opname_qty_total": "Total Stock Opname Qty",
    "lb_stock_qty": "Stock Qty",
    "lb_stock_qty_total": "Total Stock Qty",
    "lb_correction_qty": "Correction Qty",
    "lb_correction_qty_total": "Total Correction Qty",
    "lb_from": "From the store",
    "lb_to": "To the store",
    "lb_mutation_type": "Mutation Type",
    "lb_company_to_store": "Company To Store",
    "lb_store_to_store": "Store To Store",
    "lb_store_to_company": "Store To Company",
    "lb_to_empty": "To can't be null",
    "lb_from_empty": "From can't be null",
    "lb_store_more_than_one": "Mutations require more than one store. Please add new store first.",
    "lb_store_same": "Can't mutaion to the same store.",
    "lb_total_bruto": "Total Bruto",
    "lb_total_netto": "Total Netto",
    "lb_purchase_total": "Total Purchase",
    "lb_purchase_payment_total": "Total Purchase Payment",
    "lb_price_total": "Total Price",
    "lb_return_purchase_total": "Total Return Purchase",
    "lb_selling_total": "Total Selling",
    "lb_qty_residue": "Qty Residue",
    "lb_qty_non_delivery": "Total Qty Non Delivered",
    "lb_return_no": "Return No",
    "lb_return_qty_total": "Total Qty Return",
    "lb_return_total": "Total Return",
    "lb_mutation_no": "Mutation No",
    "lb_initial": "Initial",
    "lb_in": "In",
    "lb_out": "Out",
    "lb_last": "Last",
    "lb_sn": "Serial Number",
    "lb_total_nota": "Total Nota",
    "lb_giro_total": "Total Giro",
    "lb_debit_credit_total": "Total Credit\/Debit",
    "lb_cash_total": "Total Cash",
    "lb_correction_no": "Correction No",
    "lb_saldo": "Saldo",
    "lb_initial_balance": "Initial Balance",
    "lb_final_balance": "Final Balance",
    "lb_total_transaction": "Total Transaction",
    "lb_sales_store": "Sales Store",
    "lb_stock_report": "Stock Report",
    "lb_sales_ho": "Sales HO",
    "lb_outstanding_delivery": "Outstanding Delivery",
    "lb_sales_book": "Sales Book",
    "lb_purchase_book": "Purchase Book",
    "lb_voucher": "Voucher",
    "lb_ar_card": "Receivables Card",
    "lb_ap_card": "Payable Card",
    "lb_ar_saldo": "Receivables Saldo",
    "lb_ap_saldo": "Payable Saldo",
    "lb_ar_age": "Age Of Receivables",
    "lb_ap_age": "Age Of Payable",
    "lb_balance_sheet": "Balance Sheet",
    "lb_loss_profit": "Loss and Profit",
    "lb_ledger": "Ledger",
    "lb_all_company": "All Company",
    "lb_all_store": "All Store",
    "lb_aset": "Aset",
    "lb_liabilities": "Liabilities",
    "lb_warehouse_code_note": "Left blank, Warehouse code will be generate automatically by system",
    "lb_warehouse": "Warehouse",
    "lb_warehouse_select": "Select Warehouse",
    "lb_warehouse_name": "Warehouse Name",
    "lb_warehouse_without": "Without Warehouse",
    "lb_warehouse_from": "From Warehouse",
    "lb_warehouse_to": "To Warehouse",
    "lb_stock_receipt": "Stock Receipt",
    "lb_good_issue": "Good Issue",
    "lb_stock_issue": "Stock Issue",
    "lb_partner_type": "Partner Type",
    "lb_top": "TOP",
    "lb_add_new_contact": "+ Add new contact",
    "lb_add_new_phone": "+ Add new phone number",
    "lb_add_new_addr": "+ Add new address",
    "lb_change": "Change",
    "v_insert_voucher": "Silakan masukan kode voucher anda"
}});