var language_app; $(document).ready(function(){ language_app = {
    "profile": "Profile",
    "lb_company_logo": "Company Logo",
    "lb_company_name": "Company Name",
    "lb_email": "Email Address",
    "lb_phone": "Phone Number",
    "lb_password": "Password",
    "lb_password_confirm": "Confirm Password",
    "lb_name": "Name",
    "lb_first_name": "First Name",
    "lb_last_name": "Last Name",
    "lb_fullname": "Fulll Name",
    "lb_address": "Address",
    "lb_pos_code": "Postal Code",
    "lb_city": "City",
    "lb_province": "Province",
    "lb_state": "State",
    "lb_country": "Country",
    "lb_action": "Action",
    "lb_expire": "Expire",
    "lb_device": "Device",
    "lb_date": "Date",
    "lb_startdate": "Start Date",
    "lb_enddate": "End Date",
    "lb_transaction_no": "Transaction No",
    "lb_transaction_name": "Transaction Name",
    "lb_search": "Search",
    "lb_search_data": "Search Data",
    "lb_package": "Package",
    "lb_status_remark": "Status & Remark",
    "lb_voucher_package": "Voucher Package",
    "lb_voucher_qty": "Voucher Quantity",
    "lb_amount": "Amount",
    "lb_qty": "Quantity",
    "lb_bank": "Bank",
    "lb_day": "Day",
    "lb_week": "Week",
    "lb_month": "Month",
    "lb_year": "Year",
    "lb_yes": "Yes",
    "lb_no": "No",
    "lb_voucher_code": "Voucher Code",
    "lb_group_name": "Group Name",
    "lb_member_group": "Member Group",
    "lb_headgroup": "Head Group",
    "lb_remark": "Remark",
    "lb_remark_employee": "Remark Employee",
    "lb_location_remark": "Location (Mark your business partner location on the map below)",
    "lb_t_status": "Transaction Status",
    "lb_author": "Author",
    "lb_category": "Category",
    "lb_publish": "Publish",
    "lb_unpublish": "Unpublish",
    "lb_meetwith": "Meet With",
    "lb_group_report": "Group Report",
    "lb_employee_name": "Employee Name",
    "lb_use_date": "Use Date",
    "lb_minute": "Minute",
    "lb_time": "Time",
    "lb_employee_history": "Employee's Location History",
    "lb_add_new_transaction": "Add New Transaction",
    "lb_add_new_message": "Add New Message",
    "lb_add_new_employee": "Add New Employee",
    "lb_add_new_customer": "Add New Customer",
    "lb_add_new_group": "Add New Group",
    "lb_add_new_content": "Add New Content",
    "lb_subject": "Subject",
    "lb_message": "Message",
    "lb_all": "All",
    "lb_login_account": "Login Account",
    "lb_enter_verificationcode": "Enter Verification Code",
    "lb_have_account": "Already have an account?",
    "lb_no_account": "Don't have an account yet ? ",
    "lb_register_now": "Register Now",
    "lb_register_account": "Register Account",
    "lb_forgot_password": "Forgot password ?",
    "lb_reset_password": "Reset Password",
    "lb_send": "Send",
    "lb_verification_account": "Verification Account",
    "lb_resend_verification": "Resend verification code",
    "lb_user_another_account": "Use another account",
    "lb_customer_address": "Customer Address",
    "lb_customer_route": "Customer Route",
    "lb_customer_segment": "Customer Segment",
    "lb_apply": "Apply",
    "lb_help_center": "Help Center",
    "lb_total_employee_today": "Total Employee Today",
    "lb_total_troute_today": "Total Transaction Route Today",
    "lb_total_complete_route_today": "Total Complete Route Today",
    "lb_location_employee_today": "Employee's Location Today",
    "lb_status_employee": "Status Employee",
    "lb_finish": "Finish",
    "lb_checkin": "Check In",
    "lb_checkout": "Check Out",
    "lb_language": "Language",
    "lb_english": "English",
    "lb_indonesia": "Indonesia",
    "lb_check": "Check",
    "lb_history": "History",
    "lb_employee_checkin": "Employee Check In",
    "lb_employee_checkout": "Employee Check Out",
    "lb_expire_date": "Expire Date",
    "lb_description": "Description",
    "lb_logout": "Logout",
    "lb_user_account": "User Account",
    "lb_manage": "Management",
    "lb_company": "Company",
    "lb_t_voucher": "Transaction Voucher",
    "lb_admin": "Administration",
    "lb_buy_voucher": "Buy Voucher",
    "lb_company_info": "Company Information",
    "lb_master": "Master",
    "lb_customer": "Customer",
    "lb_employee": "Employee",
    "lb_employee_group": "Employee Group",
    "lb_transaction": "Transaction",
    "lb_broadcast_msg": "Broadcast Message",
    "lb_t_route": "Employee Route Transaction",
    "lb_last_position": "Last Position Empoyee",
    "lb_report": "Report",
    "lb_employee_route": "Employee Route",
    "lb_route_employee": "Rounting Employee",
    "lb_employee_visit_time": "Employee Visiting Time",
    "lb_remark_note": "Remark and Note Transaction",
    "lb_employee_visit": "Employee Visit",
    "lb_content": "Content",
    "lb_add_content": "Add Content",
    "lb_blog": "Blog",
    "lb_faq": "FAQ",
    "lb_setting": "Setting",
    "lb_op_save_customer": "Option Save Customer",
    "lb_detail_info": "Info Detail",
    "lb_total_distance": "Total Distance",
    "lb_duration": "Duration",
    "lb_customer_place": "Customer Place",
    "lb_customer_location": "Customer Location",
    "lb_customer_radius": "Customer Radius",
    "lb_total_visit": "Total Visit",
    "lb_total_route": "Total Route",
    "lb_total_plan_route": "Total Planned Route",
    "lb_total_miss_route": "Total Missed Route",
    "lb_total_unplan_route": "Total Unplanned Route",
    "lb_checkin_address": "Check In Address",
    "lb_checkout_address": "Check Out Address",
    "lb_checkin_time": "Check In Time",
    "lb_checkout_time": "Check Out Time",
    "btn_save_change": "Save Changes",
    "btn_save_user_account": "Save User Account",
    "btn_save_company": "Save Company Information",
    "btn_save": "Save",
    "btn_close": "Close",
    "btn_cancel": "Cancel",
    "btn_view": "View",
    "btn_view_voucher": "View Voucher",
    "btn_undelete": "Undelete",
    "btn_delete": "Delete",
    "btn_edit": "Edit",
    "btn_add_customer": "Add New Customer",
    "btn_buy_voucher": "Buy Voucher",
    "btn_skip": "Skip",
    "btn_confirmation": "Confirmation",
    "btn_unlink": "Unlink",
    "btn_generate_token": "Generate Token",
    "btn_set_superadmin": "Set Super Admin",
    "btn_save_ascustomer": "Save as customer",
    "btn_delete_privilege": "Delete Privilege",
    "btn_detail": "Detail",
    "btn_view_serial": "View Serial",
    "btn_customer_price": "Customer Price",
    "btn_active": "Active",
    "btn_nonactive": "Nonactive",
    "btn_back": "Back",
    "btn_action": "Action",
    "lb_choose_voucher_package": "Choose Voucher Package",
    "lb_choose_voucher_qty": "Choose Voucher Quantity",
    "lb_choose_headgroup": "Choose Head Group",
    "lb_choose_t_status": "Choose Transaction Status",
    "lb_choose_report": "Choose Report",
    "lb_chosse_employee_name": "Choose Employee Name",
    "lb_choose_company_name": "Choose Company Name",
    "lb_choose_minute": "Choose Minute",
    "lb_choose_customer": "Choose Customer Name",
    "lb_note": "Note",
    "note_voucher": "Account Number and Transfer Amount will be sent by Email To facilitate checking the number of transfers will be added a unique number. Example IDR. 49,123.00",
    "note_voucher2": "Purchase of voucher above 17:00 WIB, will be processed the next day.",
    "note_employee": "Master Employee is used to manage Sales, Technician, Courier, Driver, etc.",
    "note_img": "File size max 2mb, format (PNG, JPG, JPEG)",
    "note_forgot_password": "Instructions have been sent, please check your email",
    "note_register": "Register a new account successfully, please check your email or mobile number to verify your account",
    "v_email_empty": "Please fill out email address",
    "v_email_not_registered": "Sorry your email address not registered",
    "v_password_empty": "Please fill out password",
    "v_password_wrong": "Password is wrong",
    "v_account_deadactive": "sorry your account is not active",
    "v_account_not_headgroup": "sorry your account is not head group",
    "v_email_already": "An account with this email address already exists",
    "v_phone_already": "An account with this phone number already exists",
    "v_email_format": "Email address format incorrect",
    "v_name_empty": "Please fill out name",
    "v_phone_empty": "Please fill out phone number",
    "v_company_name_empty": "Please fill out company name",
    "v_company_not_registered": "Company not registered",
    "v_employee_404": "Employee Account not found",
    "v_company_deadactive": "Your company account has not been activated.",
    "v_account_deadactive_cek": "Your account has not been activated. Please check your registered email or phone number to verification Company Account.",
    "v_date_empty": "Please fill out date",
    "v_subject_empty": "Please fill out subject",
    "v_message_empty": "Please fill out message",
    "v_select_voucher_package": "Please choose voucher package",
    "v_select_bank": "Please choose bank",
    "v_select_qty": "Please choose quantity",
    "v_transfer_date_empty": "Please fill out transfer date",
    "v_account_bank_empty": "Please fill out account name",
    "v_account_number_empty": "Please fill out account number",
    "v_transfer_amount": "Please fill out transfer amount",
    "v_group_name": "Please fill out group name",
    "v_headgroup": "Please fill out head group",
    "v_membergroup": "Please fill out member group",
    "v_fullname": "Please fill out full name",
    "v_customer_name": "Please fill out customer name",
    "v_login_fail": "Login Failed",
    "v_password_reset": "Your password has been reset, please try to log in",
    "v_verificationcode_empty": "please fill out your verification code",
    "v_verificationcode_wrong": "Your verification code it is wrong",
    "v_verificationcode_expire": "Your verification code has expired, please resend a new verification number",
    "v_verificationcode_success": "Verification account successfully",
    "v_sendnew_verificationcode": "New verification code has been send to email address",
    "v_sendnew_verificationcode_fail": "failed to send verification of new code to email address",
    "v_sendnew_verificationcode2": "New verification code has been send to phone number",
    "v_sendnew_verificationcode_fail2": "failed to send verification of new code to phone number",
    "v_xchange_resend_vercode1": "Change email address and send a new verification code failed",
    "v_xchange_resend_vercode2": "Change phone number and send a new verification code failed",
    "v_achange_resend_vercode1": "Change email address successfully and",
    "v_achange_resend_vercode2": "Change phone number successfully and",
    "v_password1": "Your password must contain at least 8 characters!",
    "v_password2": "Your password must contain at least 1 number!",
    "v_password3": "Your password must contain at least 1 capital letter!",
    "v_password4": "Your password must contain at least 1 lowercase letter!",
    "v_address_empty": "Please fill out address",
    "lb_selling": "Sales Order",
    "lb_sellingno": "Sales Order No",
    "lb_selling_date": "Sales Order Date",
    "lb_deliveryno": "Delivery No",
    "lb_deliveryqty": "Qty Delivery",
    "lb_purchase": "Purchase Order",
    "lb_purchase2": "Purchase",
    "lb_purchaseno": "Purchase No",
    "lb_goodrc": "Good Receipt",
    "lb_goodrcno": "Receive No",
    "lb_goodrc_date": "Receive Date",
    "lb_invoicear": "Receivables Invoice",
    "lb_invoiceap": "Payable Invoice",
    "lb_delivery": "Item Delivery",
    "lb_delivery_total": "Total Item Delivery",
    "lb_delivery1": "Delivery",
    "lb_paymentar": "Receivables Payment",
    "lb_paymentap": "Payable Payment",
    "lb_returnar": "Sales Return",
    "lb_returnar_total": "Total Sales Return",
    "lb_returnap": "Purchase Return",
    "lb_correctionar": "Receivables Correction",
    "lb_correctionap": "Payable Correction",
    "lb_correctionstore": "Store Correction",
    "lb_paymentstore": "Sales Payment",
    "lb_return_receipt": "Return Receipt",
    "lb_journal": "Journal",
    "lb_sales_retail": "Sales Retail",
    "lb_cost_sold": "Cost Of Goods Sold",
    "lb_stock_opname": "Stock Opname",
    "lb_stock_correction": "Stock Correction",
    "lb_stock_mutation": "Stock Mutation",
    "lb_cash": "Cash",
    "lb_giro": "Giro",
    "lb_girono": "Giro No",
    "lb_bank_name": "Bank Name",
    "lb_bank_acount": "Account Name",
    "lb_bank_acountno": "Account No",
    "lb_transfer": "Transfer",
    "featuresx": "Pipesys Features",
    "features": "Features",
    "price": "Price",
    "user": "User",
    "month": "Month",
    "year": "Year",
    "module": "Module",
    "person": "Person",
    "max": "Max",
    "login": "Login",
    "try_free": "Try for free",
    "try_free_now": "Try it for free now",
    "free_trial": "Free trial for 30 days",
    "help_center": "Help Center",
    "another_product": "Another Product",
    "contact": "Contact",
    "module_detail": "Module Details",
    "additional": "Additional User",
    "buy_voucher": "Buy Voucher",
    "fitur_dashboard": "Dashboard",
    "fitur_purchase": "Purchase Module",
    "fitur_sales": "Sales Module",
    "fitur_stock": "Stock of goods",
    "fitur_accounting": "Accounting",
    "lb_try_it_now": "Try It Now",
    "fitur_dashboard_txt": "Attractive and informative dashboard display data on purchase, sales and inventory",
    "fitur_purchase_txt": "Help the purchase process start from purchase order, good receipt, return purchase until payment payable",
    "fitur_sales_txt": "Help the sales process process start from sales order, delivery, return sales until payment payable",
    "fitur_stock_txt": "Help monitor in-out stock such as transaction correction stock, stock opname, mutation stock",
    "fitur_accounting_txt": "Help to prepare financial report start from automatic journal on each transaction and record income & outcome cash flow and bank",
    "slogan": "Pipesys is the ERP system used to help business process in purchasing, sales, inventory, and accounting transactions.",
    "slide_1": "Manage business processes more easily with Pipesys (POS)",
    "lb_choose_qty": "Please choose Qty",
    "lb_email_format": "Invalid Email format",
    "lb_email_empty": "Email can't be null",
    "lb_name_empty": "Name can't be null",
    "lb_store_name_empty": "Store name can't be null",
    "lb_information": "Information",
    "lb_incomplete_form": "Incomplete form",
    "lb_alert_order": "Are you sure want to order?",
    "lb_order": "Order",
    "lb_canceled": "Canceled",
    "lb_name_validate": "Only letters and space allowed",
    "lb_type_empty": "Type can't be null",
    "lb_first_name_empty": "First name can't be null",
    "lb_lasr_name_empty": "Last name can't be null",
    "lb_instruction": "Instructions sent, Please check your e-mail",
    "lb_reset": "Reset",
    "lb_send_to_email": "Send to Email",
    "lb_send_to_phone": "Send to Phone Number",
    "lb_user_info": "User Information",
    "lb_agree_terms": "I agree with terms and policy",
    "lb_noted": "Noted",
    "lb_email_provide": "Please provide a valid email address, payment instruction and voucher code will be sent to the email address provided here after completeting the order.",
    "lb_account_ex": "Account Number and Transfer Amount will be sent by Email To facilitate checking the number of transfers will be added a unique number. Example IDR. 49,123.00",
    "lb_voucer_continue": "Continue Buy Voucher",
    "lb_voucher_module": "Module \/ Device Voucher Qty",
    "lb_voucher_module_choose": "Choose Voucher Module \/ Devices Quantity",
    "lb_voucher_module_amount": "Total Price : Module \/ Device Voucher",
    "lb_voucher_user": "Additional User Voucher Qty",
    "lb_voucher_user_choose": "Choose Voucher Additional User Quantity",
    "lb_voucher_user_amount": "Total Price : Additional User Voucher",
    "lb_voucher_additional": "Voucher Additional User",
    "lb_voucher_notif": "Thank you for purchasing voucher from us",
    "lb_voucher_code1": "Your order code is ",
    "lb_voucher_confirm": "You will receive a confirmation email with your order details",
    "lb_voucher_detail": "Detail Order",
    "lb_voucher_type": "Voucher Type",
    "lb_voucher_type_choose": "Please choose voucher type",
    "lb_voucher_use": "Use Voucher",
    "lb_voucher_empty": "Voucer Code can't be null",
    "lb_voucher_not_found": "Voucher Code not found",
    "lb_user_expired": "Expired User",
    "lb_user_expired_validate": "Your Account has expired",
    "lb_store": "Store",
    "lb_for_additional": "for additional user",
    "lb_additional_qty": "Additional Quantity",
    "lb_module_qty": "Module \/ Devices Quantity",
    "lb_module_device": "Module \/ Devices",
    "lb_use_voucher": "Voucher Use",
    "lb_voucher_enter": "Enter Voucher Code",
    "lb_voucher_enter_validate": "Please enter voucher code",
    "lb_module_validate": "Please select module",
    "lb_total_amount": "Grand Total",
    "lb_check_out": "Checkout",
    "lb_loading": "Loading",
    "lb_reload": "Reload",
    "lb_close": "Close",
    "lb_add_new": "Add New",
    "lb_error_data": "Error data, please try again",
    "lb_error_data1": "Error deleting data",
    "lb_user_not_found": "Account user not found",
    "lb_success": "Success",
    "lb_days": "Days",
    "lb_hours": "Hours",
    "lb_minutes": "Minutes",
    "lb_seconds": "Seconds",
    "lb_startdate_select": "Select Start Date",
    "lb_enddate_select": "Select End Date",
    "lb_total_sales_amount": "Total Sales Amount",
    "lb_total_gross_margin": "Total Gross Margin",
    "lb_total_purchase_amount": "Total Purchase Amount",
    "lb_module_device_expire": "Module\/Devices & Additional User Expires",
    "lb_module_expire": "Module Expire",
    "lb_day_left": "Day Left",
    "lb_device_expire": "Device Expire",
    "lb_sales": "Sales",
    "lb_total_by_category": "Total Sales By Category",
    "lb_top_by_category": "Top 5 Sales by Category",
    "lb_top_by_customer": "Top 10 Sales by Customer",
    "lb_top_by_city": "Top 10 Sales by City",
    "lb_total_sales_transaction": "Total Sales Transaction",
    "lb_outstanding_sales": "Outstanding Sales",
    "lb_total_store_sales": "Total Store Sales",
    "lb_total_store": "Total Store",
    "lb_total_customer": "Total Customer",
    "lb_open_selling": "Open Selling",
    "lb_total_open_selling": "Total Open Selling",
    "lb_overdude_selling": "Overdue Selling",
    "lb_total_overdude_selling": "Total Overdue Selling",
    "lb_payment_receivable": "Payment Receivable",
    "lb_total_payment": "Total Payment",
    "lb_purchase1": "Purchase",
    "lb_total_purchse_qty": "Total Purchase Quantity",
    "lb_total_receipt_qty": "Total Good Receipt Quantity",
    "lb_total_purchse_trans": "Total Purchase Transaction",
    "lb_total_penerimaan_trans": "Total Good Receipt Transaction",
    "lb_total_product_return": "Total Product Return",
    "lb_open_purchase": "Open Purchases",
    "lb_open_purchase_total": "Total Open Purchases",
    "lb_overdude_purchase": "Overdue Purchases",
    "lb_overdude_purchase_total": "Total Overdue Purchases",
    "lb_payment_purchase": "Payment Purchases",
    "lb_payment_purchase_total": "Total Payment Purchases",
    "lb_inventory": "Inventory",
    "lb_inventory_select": "Select Inventory",
    "lb_total_stock": "Total Stock",
    "lb_stock_minimal": "Stock Product Minimal",
    "lb_total_product": "Total Product",
    "lb_total_omset": "Total Omset",
    "lb_omset": "Omset",
    "lb_total_sales_store_ar": "Total Sales Store Receivable",
    "lb_total_net_profit": "Total Net Profit",
    "lb_total_net_balance": "Total Net Balance Sheet",
    "lb_ac_watchlist": "Account Watchlist",
    "lb_total": "Total",
    "lb_sales_by_hour": "Sales by Hour",
    "lb_store_location": "Store Location",
    "lb_additional_expire": "Additional User Expire",
    "lb_product_code": "Product Code",
    "lb_product_name": "Product Name",
    "lb_minimal_stock": "Minimal Stock",
    "lb_residu": "Residu Stock",
    "lb_select_file": "Please Select File",
    "lb_select_type": "Select Type",
    "lb_deleted": "Yes, delete it!",
    "lb_deleted1": "Deleted",
    "lb_ask": "Are you sure?",
    "lb_undeleted": "Yes, undelete it!",
    "lb_canceled1": "No, cancel it!",
    "lb_transaction_status": "Status Transaction",
    "lb_account_no": "Account Number",
    "lb_transfer_amount": "Transfer Amount",
    "lb_voucher_confirm1": "Voucher Confirmation",
    "lb_add_form_voucher": "Add Form Voucher",
    "lb_delete_form_voucher": "Delete Form Voucher",
    "lb_trans_process": "Transaction Process",
    "lb_trans_success": "Transaction Success",
    "lb_trans_cancel": "Transaction Cancel",
    "lb_add_bank": "Add Bank",
    "lb_branch_name": "Branch Name (Bank)",
    "lb_remove_bank": "Remove Bank",
    "lb_remove_module": "Remove Module",
    "lb_bank_min_1": "Sorry, Bank Minimum 1",
    "lb_bank_max": "Sorry, Bank Maximum Added",
    "lb_save_setting": "Save Setting",
    "lb_ac": "Accounting",
    "lb_type": "Type",
    "lb_image": "Image",
    "lb_selling1": "Selling",
    "lb_fax": "Fax",
    "lb_remove": "Remove",
    "lb_process": "Process",
    "lb_used_by_name": "Used By (Name)",
    "lb_used_by_com": "Used By (Company Name)",
    "lb_currency": "Currency",
    "lb_select_module": "Select Module",
    "lb_module_purchase": "Module Purchase",
    "lb_module_selling": "Module Selling",
    "lb_module_inventory": "Module Inventory",
    "lb_module_ac": "Module Accounting",
    "lb_devices": "Devices",
    "lb_stock": "Stock",
    "lb_mutation": "Mutation",
    "lb_cash_bank": "Cash \/ Bank",
    "lb_payment": "Payment",
    "lb_correction": "Correction",
    "lb_invoice": "Invoice",
    "lb_return": "Return",
    "lb_recipt": "Receipt",
    "lb_npwp": "NPWP",
    "lb_ok": "OK",
    "lb_amount_digint": "Amount \/ Price Decimal Digit",
    "lb_decimal_digit": "Quantity Decimal Digit",
    "lb_cost_method": "Costing Method",
    "lb_average": "Average",
    "lb_negative": "Negative Stock",
    "lb_allow": "Allow",
    "lb_warning": "Warning",
    "lb_block": "Block",
    "lb_send_debt": "Send Report Debt & Receivable Every",
    "lb_monday": "Monday",
    "lb_tuesday": "Tuesday",
    "lb_wednesday": "Wednesday",
    "lb_thursday": "Thursday",
    "lb_friday": "Friday",
    "lb_saturday": "Saturday",
    "lb_sunday": "Sunday",
    "lb_module_setting": "Module Setting",
    "lb_journal_manual": "Journal Manual",
    "lb_data_setting": "Data Setting",
    "lb_template_default": "Default Template Setting",
    "lb_data_default": "Default Data Setting",
    "lb_view_image": "View Image",
    "lb_manage_store": "Store & Device Management",
    "lb_store_name": "Store Name",
    "lb_store_not_found": "Store not found, Please check store again",
    "lb_location_marker": "Location (Mark your store location on the map below)",
    "lb_locked": "Locked",
    "lb_unlocked": "Unlocked",
    "lb_coa_setting": "COA Setting",
    "lb_coa_ap": "COA Payable",
    "lb_ap": "Account Payable",
    "lb_ap_temp": "Account Payable Temporary",
    "lb_tax_in": "Tax In",
    "lb_tax_out": "Tax Out",
    "lb_tax_in_temp": "Tax In Temporary",
    "lb_tax_out_temp": "Tax Out Temporary",
    "lb_discount": "Discount",
    "lb_discount_value": "Discount Value",
    "lb_coa_ar": "COA Receivable",
    "lb_ar": "Account Receivable",
    "lb_ar_temp": "Account Receivable Temporary",
    "lb_sales_temp": "Sales Temporary",
    "lb_income": "Income",
    "lb_expense": "Expense",
    "lb_delivery_cost": "Delivery Cost",
    "lb_gains_stock": "Gains Stock",
    "lb_loss_stock": "Loss Stock",
    "lb_transfer_credit": "Transfer\/Credit",
    "lb_profit_year": "Profit And Loss Current Year",
    "lb_select_data": "select data",
    "lb_code": "Code",
    "lb_level": "Level",
    "lb_coa_parent": "Parent COA",
    "lb_coa_without": "Without COA",
    "lb_product_item": "Item Product",
    "lb_product_service": "Service",
    "lb_delete": "Delete",
    "lb_selling_select": "Select Selling",
    "lb_min_qty": "Min Quantity",
    "lb_unit": "Unit",
    "lb_purchase_price": "Purchase Price",
    "lb_selling_price": "Selling Price",
    "lb_average_price": "Average Price",
    "lb_product_code_note": "Left blank, Product code will be generate automatically by system",
    "lb_product_type": "Product Type",
    "lb_product_type_select": "Select Product Type",
    "lb_serial": "Serial",
    "lb_sn_format": "Serial Number Format",
    "lb_sn_format_note": "The Serial Number will be created automatically by the system. Click here to set the serial number format",
    "lb_auto": "AUTOMATIC",
    "lb_before_tax": "Price before tax",
    "lb_product_inventory_note": "The stock will be recorded and monitored by system.",
    "lb_product_selling_note": "This item can be sell.",
    "lb_product_serial_note": "This item have serial number.",
    "lb_product_qty_note": "Min Qty used for minimal stock product information.",
    "lb_product_code_exist": "Sorry this product code has been already exist",
    "lb_product_name_empty": "Product name can't be null",
    "lb_category_empty": "Category can't be null",
    "lb_unit_empty": "Unit can't be null",
    "lb_product_serial": "Prduct Serial Number",
    "lb_import_detail": "Import Data Detail",
    "lb_failed": "Failed",
    "lb_product_insert": "Insert Master Product",
    "lb_product_update": "Update Master Product",
    "lb_category_insert": "Insert Master Category",
    "lb_category_update": "Update Master Category",
    "lb_data_not_found": "Data Not Found",
    "lb_total_data": "Total Data",
    "lb_fail": "Fail",
    "lb_file_not_found": "File not found, please reupload import file",
    "lb_next": "Next",
    "lb_saving": "Saving",
    "lb_remarks": "Remarks",
    "lb_remark_input": "Input Remark",
    "lb_qty_input": "Input Qty",
    "lb_price_input": "Input Price",
    "lb_discount_input": "Input Discount",
    "lb_average_input": "Input Average",
    "lb_attachment": "Attachment",
    "lb_file_upload": "File Upload",
    "lb_file_choose": "Choose file in brwoser",
    "lb_code_required": "Code is required and not duplicate.",
    "lb_name_not_change": "Name is required and can't change.",
    "lb_average_required": "Average Price is required.",
    "lb_price_required": "Price is required.",
    "lb_stock_op_required": "Stock Opname Qty is required.",
    "lb_stock_qty_not_change": "Stock Qty is required and can't change.",
    "lb_unit_not_change": "Unit is required and can't change.",
    "lb_remark_opsional": "Remark is opsional filed.",
    "lb_sn_reqired": "products with serial numbers must be 1 quantity and is required. and not duplicate",
    "lb_average_price_program": "Average price program and Average price input is not balance",
    "lb_product_not_found": "Product not found, Please check your data",
    "lb_product_name_not_change": "Can't change Product Name",
    "lb_unit_not_change1": "Can't change Product Unit",
    "lb_stock_qty_not_change1": "Can't change Stock Qty",
    "lb_product_code_not_found": "Product Code not found",
    "lb_product_code_or_branch_not_fount": "Product Code or Store not found",
    "lb_average_number": "Input Average Price With Number Format",
    "lb_stock_opname_qty_num": "Input Stock Opname Qty With Number Format",
    "lb_stock_qty_num": "Input Stock Qty With Number Format",
    "lb_uom": "Unit of Measurement",
    "lb_category_not_data": "Item Category is empty.",
    "lb_category_add": "Please add new Category first",
    "lb_store_required": "Store is required.",
    "lb_average_view": "View Average",
    "lb_product_store": "Product Store",
    "lb_category_code": "Category Code",
    "lb_category_name": "Category Name",
    "lb_product_download": "Download sample template Product excel file from",
    "lb_here": "here",
    "lb_file_note": "This file has preset column header required by PipeSys to import your data correctly.",
    "lb_file_entry": "Entry Data To File Template.",
    "lb_use_excell": "Use Microsoft Excel application to copy and paste your data into Pipesys import template that you just downloaded. Make sure the data you that you input corresponds to each column header provided on the import template and note below.",
    "lb_product_code_note1": "If Product Code is empty then system will auto generate product code.",
    "lb_category_code_note": "Category Code is required and can see in Master Category.",
    "lb_category_name_note": "Category Name is required and can see in Master Category.",
    "lb_product_name_requi": "Product Name is required.",
    "lb_min_qty_note": "Mininum quantity of product.",
    "lb_unit_note": "Unit is required and can se in Master Unit.",
    "lb_selling_price_requi": "Selling Price is required.",
    "lb_product_type_requi": "Pruduct Type is required, Ex: Yes, No.",
    "lb_selling_type_requi": "Selling Type is required, Ex: Yes, No.",
    "lb_serial_type_requi": "Serial Type is required, Ex: Yes, No.",
    "lb_upload_file": "Upload File",
    "lb_file_type": "After your finished with step 2, please upload the file. File needs to be in CSV (Comma Separated Values) format and ended with extension .xls",
    "lb_excell_note": "New excel format applied, if you already have one please update your excel to the latest format before uploading!",
    "lb_excell_empty": "Please Upload Excel File",
    "lb_category_inactive": "Category Code has been inactive",
    "lb_inventory_not_change": "Update can't change Inventory type",
    "lb_selling_not_change": "Update can't change Selling type",
    "lb_serial_not_change": "Update can't change Serial type",
    "lb_product_inactive": "Product Code has been inactive",
    "lb_inventory_type_empty": "If inventory type yes unit can't be null",
    "lb_price_input_format": "Input Price With Number Format",
    "lb_inventory_only_use": "Inventory Type only use Yes or No",
    "lb_selling_only_use": "Selling Type only use Yes or No",
    "lb_serial_only_use": "Serial Type only use Yes or No",
    "lb_selling_zero": "Should field Selling Price is Zero, because Selling Type is No",
    "lb_category_code_empty": "Category Code can't be null",
    "lb_category_name_empty": "Category Name can't be null",
    "lb_column_not_match": "Column not match",
    "lb_success_import": "Success import data",
    "lb_file_not_found1": "File not found, please reupload import file",
    "lb_import_alert": "NOTE: New excel format applied, if you already have one please update your excel to the latest format before uploading!",
    "lb_sales_import1": "1. Download sample template Sales excel file from",
    "lb_sales_import2": "2. Entry Data To File Template",
    "lb_sales_import3": "3. Upload File",
    "lb_sales_import1_note1": "This file has preset column header required by PipeSys to import your data correctly",
    "lb_sales_import2_note1": "Use Microsoft Excel application to copy and paste your data into Pipesys import template that you just downloaded. Make sure the data you that you input corresponds to each column header provided on the import template and note below.",
    "lb_sales_import2_note2": "Sales Code: Sales Code is required and no duplicate",
    "lb_sales_import2_note3": "Name: fill in the name of sales",
    "lb_sales_import2_note4": "Phone: fill in the Phone of sales",
    "lb_sales_import2_note5": "City: fill in the City of sales",
    "lb_sales_import2_note6": "Address: fill in the Address of sales",
    "lb_sales_import2_note7": "Remark: fill in the Remark of sales",
    "lb_sales_import3_note3": "After your finished with step 2, please upload the file. File needs to be in CSV (Comma Separated Values) format and ended with extension .xls",
    "lb_reset_data": "Reset Data",
    "lb_reset_type": "Type Reset",
    "lb_reset_only_trans": "Only Transaction",
    "lb_reset_only_trans1": "Only Transaction Data",
    "lb_reset_all": "All (Master & Transaction)",
    "lb_username": "User Name",
    "lb_reset_alert": "Are you sure want to reset data?",
    "lb_reset_note": "\"Reset Data\" will delete all master data and transaction data, All information devices in the company will be deleted, and all branches or stores will unlink the device. Please understand before using this function.",
    "lb_reset_success": "Reset Data Success",
    "lb_status_select": "Select Status",
    "lb_vendor": "Vendor",
    "lb_vendor_select": "Select Vendor",
    "lb_qty_total": "Total Quantity",
    "lb_qty_total_real": "Total Real Quantity",
    "lb_sales_select": "Select Sales",
    "lb_term": "Term",
    "lb_due_date": "Due Date",
    "lb_tax": "Tax",
    "lb_qty_stock": "Qty Stock",
    "lb_qty2": "Qty",
    "lb_qty_warehouse": "Warehouse Qty",
    "lb_qty_real": "Real Qty",
    "lb_qty_real1": "Real Quantity",
    "lb_qty_hand": "Qty in Hand",
    "lb_qty_order": "Qty Order",
    "lb_conversion": "Conversion",
    "lb_sub_total": "Sub Total",
    "lb_delivery_date": "Delivery Date",
    "lb_add_column": "Add Column",
    "lb_discount_total": "Total Discount",
    "lb_select_product_empty": "Please select product",
    "lb_product_qty_empty": "Qty product can't be null",
    "lb_sales_empty": "Sales can't be null",
    "lb_vendor_empty": "Vendor can't be null",
    "lb_address_empty": "Address can't be null",
    "lb_city_empty": "City can't be null",
    "lb_province_empty": "Province can't be null",
    "lb_billing_empty": "BillingTo can't be null",
    "lb_max_item": "Item data max",
    "lb_print": "Print",
    "lb_sales_employee": "Sales & Employee",
    "lb_code_exist": "Code has been already exist",
    "lb_sales_name": "Sales Name",
    "lb_sales_without": "Without Sales",
    "lb_sales_code": "Sales Code",
    "lb_sales_note": "Left blank, Sales Code will be generate automatically by system",
    "lb_sales_inactive": "Sales Code has been inactive",
    "lb_product_duplicate": "Product can't duplicate",
    "lb_serial_empty": "Serial number can't be null",
    "lb_serial_not_found": "Serial not found",
    "lb_product_qty_stock": "Qty product is not available",
    "lb_service_not_serial": "Product Service can't input serial number",
    "lb_serial_not_active": "Product Serial not active, can't input serial number",
    "lb_serial_qty": "Product Serial must be 1 quantity",
    "lb_serial_duplicate": "Serial Number is duplicate",
    "lb_general": "General",
    "lb_site_profile": "Site Profile",
    "lb_site_title": "Site Title",
    "lb_site_tagline": "Site Tagline",
    "lb_generate_file": "Generate File",
    "lb_generate_language": "Generate Language JS",
    "lb_logo": "Logo",
    "lb_logo_small": "Small Logo",
    "lb_telephone": "Telephone",
    "lb_whatsapp": "Whatsapp",
    "lb_address_link": "Link Address to Maps",
    "lb_technical": "Technical",
    "lb_vendor_without": "Without Customers",
    "lb_vendor_name": "Vendor Name",
    "lb_partner_code": "Partner Code",
    "lb_delivery_address": "Delivery Address",
    "lb_delivery_city": "Delivery City",
    "lb_delivery_province": "Delivery Province",
    "lb_payment_to": "Payment To",
    "lb_payment_address": "Payment Address",
    "lb_payment_city": "Payment City",
    "lb_payment_province": "Payment Province",
    "lb_total_paid": "Total Paid",
    "lb_pay_cash": "Pay Cash",
    "lb_pay_transfer": "Pay Transfer",
    "lb_pay_giro": "Pay Giro",
    "lb_transaction_type": "Transaction Type",
    "lb_balance_type": "Balance Type",
    "lb_pay_total": "Total Pay",
    "lb_total_unpaid": "Total Unpaid",
    "lb_payment_date": "Payment Date",
    "lb_payment_type": "Payment Type",
    "lb_payment_method": "Payment Method",
    "lb_transaction_date": "Transaction Date",
    "lb_select_item": "Please select item",
    "lb_payment_method_empty": "Payment Method can't be null",
    "lb_paid_incorect": "Total Payment and Total Paid is incorrect",
    "lb_coa_select": "Select COA",
    "lb_paymentno": "Payment No",
    "lb_pay_credit_debit": "Pay Debit \/ Credit",
    "lb_pay_additional": "Additional Cost",
    "lb_grand_total_sales": "Grand Total Sales",
    "lb_total_sales": "Total Sales",
    "lb_order_type": "Type Order",
    "lb_purchase_non": "Non Purchase Order",
    "lb_delivery_order": "Delivery Order No",
    "lb_receipt_qty": "Qty Receive",
    "lb_purchase_date": "Purchase Date",
    "lb_vendor_select2": "Please select vendor",
    "lb_edit": "Edit",
    "lb_cancel_alert": "Are you sure want to cancel?",
    "lb_delete_alert": "Are you sure want to delete?",
    "lb_delivery_empty": "Delivery Order Code can't be null",
    "lb_paid_exceeding": "Total Paid exceeding Total Unpaid",
    "lb_paid_empty": "Total Paid can't be null",
    "lb_receipt_name": "Receipt Name",
    "lb_purchase_qty": "Purchase Qty",
    "lb_return_qty": "Return Qty",
    "lb_receipt_qty_empty": "Qty Receive is not available",
    "lb_customer_empty": "Customer can't be null",
    "lb_remark_empty": "Remark can't be null",
    "lb_receipt_no_empty": "Receive No can't be null",
    "lb_return_date": "Return Date",
    "lb_transaction_qty": "Transaction Qty",
    "lb_sales_qty_empty": "Qty Sell is not available",
    "lb_delivery_qty_empty": "Qty delivery is not available",
    "lb_grand_total": "Grand Total",
    "lb_invoice_date": "Invoice Date",
    "lb_invoiceno": "Invoice No",
    "lb_customer_select": "Please select customer",
    "lb_customer_select1": "Select customer",
    "lb_data_exists": "Data already exists",
    "lb_total_ar_invoice": "Total AR Invoice",
    "lb_correction_type": "Correction Type",
    "lb_correction_total": "Total Correction",
    "lb_debit": "Debit",
    "lb_credit": "Credit",
    "lb_correction_total_ap": "Total Correction AP",
    "lb_correction_total_ar": "Total Correction AR",
    "lb_store_select": "Select Store",
    "lb_input_nominal": "Input Nominal",
    "lb_correction_total_empty": "Total Correction can't null",
    "lb_store_select1": "Please select store",
    "lb_product_inventory_active": "Product Inventory must be active",
    "lb_product_duplicate2": "Product Code is duplicate",
    "lb_open": "Open",
    "lb_unpaid": "Unpaid",
    "lb_paid": "Paid",
    "lb_customer_name": "Customer Name",
    "lb_delivery_to": "Delivery To",
    "lb_billing_to": "Billing To",
    "lb_product_preorder": "Product is pre order",
    "lb_delivery_to_empty": "DeliveryTo can't be null",
    "lb_sales_order_non": "Non Sales Order",
    "lb_sales_qty": "Qty Sales",
    "lb_sales_all": "All Sales Order No",
    "lb_select": "Select",
    "lb_date_empty": "Date can't be null",
    "lb_total_ar_empty": "Total ar invoice can't be null",
    "lb_grand_total_empty": "Grand total can't be null",
    "lb_total_not_same": "Total Payment and Total AR Invoice must be same",
    "lb_sales_no_select": "Please Select Sales No",
    "lb_sale": "Sale",
    "lb_total_debit": "Total Debit",
    "lb_total_credit": "Total Credit",
    "lb_coa_code": "Coa Code",
    "lb_coa_name": "Coa Name",
    "lb_debit_or_credit_empty": "Debit or credit can't be null",
    "lb_coa_select1": "Please select COA",
    "lb_debit_credit_not_same": "Total debit and credit not balance",
    "lb_average_program": "Average Price Program",
    "lb_stock_opname_qty": "Stock Opname Qty",
    "lb_stock_opname_qty_total": "Total Stock Opname Qty",
    "lb_stock_qty": "Stock Qty",
    "lb_stock_qty_total": "Total Stock Qty",
    "lb_correction_qty": "Correction Qty",
    "lb_correction_qty_total": "Total Correction Qty",
    "lb_from": "From the store",
    "lb_to": "To the store",
    "lb_mutation_type": "Mutation Type",
    "lb_company_to_store": "Company To Store",
    "lb_store_to_store": "Store To Store",
    "lb_store_to_company": "Store To Company",
    "lb_to_empty": "To can't be null",
    "lb_from_empty": "From can't be null",
    "lb_store_more_than_one": "Mutations require more than one store. Please add new store first.",
    "lb_store_same": "Can't mutaion to the same store.",
    "lb_total_bruto": "Total Bruto",
    "lb_total_netto": "Total Netto",
    "lb_purchase_total": "Total Purchase",
    "lb_purchase_payment_total": "Total Purchase Payment",
    "lb_price_total": "Total Price",
    "lb_return_purchase_total": "Total Return Purchase",
    "lb_selling_total": "Total Selling",
    "lb_qty_residue": "Qty Residue",
    "lb_qty_non_delivery": "Total Qty Non Delivered",
    "lb_return_no": "Return No",
    "lb_return_qty_total": "Total Qty Return",
    "lb_return_total": "Total Return",
    "lb_mutation_no": "Mutation No",
    "lb_initial": "Initial",
    "lb_in": "In",
    "lb_out": "Out",
    "lb_last": "Last",
    "lb_sn": "Serial Number",
    "lb_total_nota": "Total Nota",
    "lb_giro_total": "Total Giro",
    "lb_debit_credit_total": "Total Credit\/Debit",
    "lb_cash_total": "Total Cash",
    "lb_correction_no": "Correction No",
    "lb_saldo": "Saldo",
    "lb_initial_balance": "Initial Balance",
    "lb_final_balance": "Final Balance",
    "lb_total_transaction": "Total Transaction",
    "lb_sales_store": "Sales Store",
    "lb_stock_report": "Stock Report",
    "lb_sales_ho": "Sales HO",
    "lb_outstanding_delivery": "Outstanding Delivery",
    "lb_sales_book": "Sales Book",
    "lb_purchase_book": "Purchase Book",
    "lb_voucher": "Voucher",
    "lb_ar_card": "Receivables Card",
    "lb_ap_card": "Payable Card",
    "lb_ar_saldo": "Receivables Saldo",
    "lb_ap_saldo": "Payable Saldo",
    "lb_ar_age": "Age Of Receivables",
    "lb_ap_age": "Age Of Payable",
    "lb_balance_sheet": "Balance Sheet",
    "lb_loss_profit": "Loss and Profit",
    "lb_ledger": "Ledger",
    "lb_all_company": "All Company",
    "lb_all_store": "All Store",
    "lb_aset": "Aset",
    "lb_liabilities": "Liabilities",
    "lb_warehouse_code_note": "Left blank, Warehouse code will be generate automatically by system",
    "lb_warehouse": "Warehouse",
    "lb_warehouse_select": "Select Warehouse",
    "lb_warehouse_name": "Warehouse Name",
    "lb_warehouse_without": "Without Warehouse",
    "lb_warehouse_from": "From Warehouse",
    "lb_warehouse_to": "To Warehouse",
    "lb_stock_receipt": "Stock Receipt",
    "lb_good_issue": "Good Issue",
    "lb_stock_issue": "Stock Issue",
    "lb_partner_type": "Partner Type",
    "lb_top": "TOP",
    "lb_add_new_contact": "+ Add new contact",
    "lb_add_new_phone": "+ Add new phone number",
    "lb_add_new_addr": "+ Add new address",
    "lb_change": "Change",
    "v_insert_voucher": "Silakan masukan kode voucher anda"
}});